// TypeData.js
const TypeData = [
  'Pipe',
  'Elbow',
  'Tee',
  'Reducer Concentric',
  'Reducer Eccentric',
  'Saddle',
  'Nozzle',
  'Flange',
  'Blind Flange',
  'Lamination Joint',
  'Lamination Kit',
  'Certificate',
  'Test Report',
  'Build-up',
  'Cover Slab',
  'Short Reducer',
  'Saddle - Cemented',
  'Saddle - Buildup',
  'End Cap',
  'Cement Joint',
  'Wye Branch',
  'Eccentric Reducer',
  'Concentric Reducer',
  'Adaptor',
  'Coupler',
  'Puddle Flange',
  'Z Ties',
  'Short Pipe',
  'Customer Short Pipe',
  'Manhole',
  'Structural Manhole',
  'Benching Unit',
  'Spacer Ring',
  'Cowl',
  'Cross Tee',
  'Reinforcement Lamination Kit',
  'Reinforcement Lamination Joint',
  'Elbow Body',
  'Saddle Pipe',
  'Nipple',
  'Elbow Made on Shell',
  'Elbow Shell',
  'Tee Made on Shell',
  'Tee Shell',
  'Wye Made on Shell',
  'Wye Shell',
  'Concentric Reducer Made on Shell',
  'Concentric Reducer Shell',
  'Eccentric Reducer Made on Shell',
  'Eccentric Reducer Shell',
  'Stiffner',
  'Pup Joint',
  'Base Plate',
  'Cover Slab-Str MH',
  'Swage',
  'Reducer Coupler',
  'Reducer Bushing',
  'Antifloatation and Ringcover',
  'Shutter and Backdrop',
  'Flange FR Cover'
];

const SubTypeData = [
  "Standard",
  "DBC CN Coupler Pipe",
  "DBC SLJ Coupler Pipe",
  "AC Coupler Pipe (18)",
  "AC Coupler Pipe (24)",
  "WS TB Coupler Pipe",
  "WS CB Coupler Pipe",
  "Threaded Coupler Pipe",
  "Valve Chamber Structural  Shaft",
  "Manhole Structural  Shaft",
  "Manhole Shell",
  "Tank Shell",
  "Preinsulated Jacket",
  "Jacking Standard Pipe",
  "Jacking Adjustment Pipe",
  "Jacking IJS Lead Pipe",
  "Jacking ISJ Trail Pipe",
  "Sliplining Pipe",
  "Hybrid Restrained OD Controlled.",
  "Molded Fitting",
  "Mitered Fitting",
  "Invert Tee, Mitered",
  "Lamination: Straight Joint",
  "Lamination: Mitered Elbow",
  "Lamination: Mitered Tee",
  "Lamination: Mitered Other",
  "2 Port Connections",
  "3 Port Connections",
  "4 Port Connections",
  "Adaptor",
  "Adjusting",
  "Adjusting Elbow",
  "Adjusting Shop Straight",
  "Air Valve",
  "Base Plate",
  "Benching",
  "Blind",
  "Closure",
  "Collar",
  "Compression",
  "Concentric Reducer",
  "Coupler to Cover Slab (Tanks)",
  "Dome Top with Puddle Flange",
  "Dome Top without Puddle Flange",
  "Double",
  "Duckfoot Baseplate",
  "Duckfoot Elbow",
  "Eccentric Reducer",
  "FB End",
  "Field Constructed Coupler",
  "Field Constructed Coupler Oil and Gas",
  "Field Straight",
  "Field Straight Chemical Application",
  "Fixation",
  "Flange",
  "Flat Top with Puddle Flange",
  "Flat Top without Puddle Flange",
  "For AC18 Coupler",
  "For AC24 Coupler",
  "For Butterfly Valve",
  "For Coupler",
  "FR Flange cover",
  "FS End",
  "Grounding",
  "Heavy Duty",
  "Hubless",
  "Invert",
  "Jacking Pipe Hybrid-CF",
  "Jacking Pipe With SS",
  "Lifting Block and Shear key",
  "Loose",
  "Machined",
  "Man Way",
  "MH Cover Slab",
  "MH Liner",
  "Nipple - Copper Nickel",
  "Nipple - Duplex",
  "Nipple - Monel",
  "Nipple - Stainless Steel 316L",
  "Nipple - Titanium",
  "Nipple- Stainless Steel 316",
  "Nozzle",
  "Orifice",
  "Over Lay",
  "Port",
  "PU",
  "Rectangle",
  "Reducer Bushing",
  "Reducer Coupler",
  "Ribbing",
  "Round",
  "Round Center Opening",
  "Round Side Opening",
  "Sealing Puddle Flange",
  "Shop Joint",
  "Shop Straight",
  "Single",
  "SlipLinning Pipe",
  "SN",
  "Square",
  "Square Center Opening",
  "Square Side Opening",
  "Structural Manhole",
  "Stub end",
  "Swage",
  "Tank",
  "Tank End Cap",
  "Tank Liner",
  "Test",
  "Thrust Puddle Flange",
  "Undrilled",
  "WaterJet Pipe",
  "Wear",
  "With Adapter",
  "With EST Pipe",
  "With Flange",
  "With PCT HC Pipe",
  "With Pipe",
  "With PST Pipe",
  "With VCT HC Pipe",
  "Wye Branch"
];

const Composition = [
  "CN Pipe, Std. Sand Core",
  "55° Helical Winding",
  "63° Helical Winding",
  "73° Helical Winding",
  "60°/6° Helical Winding",
  "60°/25° Helical Winding",
  "55°/80° Helical Winding",
  "CN Pipe Sand Max 20%",
  "CN Pipe Sand Max 25%",
  "CN Pipe Sand Max 30%",
  "CN Pipe Sand Max 35%",
  "CN Pipe Sand Max 40%",
  "CN Pipe Sand Max 45%",
  "CN Pipe Sand Max 50%",
  "CN Pipe Full Glass",
  "CN Pipe Conventional",
  "CT Pipe High Chop",
  "CT Pipe Medium Chop",
  "CT Pipe Axial Tape",
  "CT Pipe Sandwich Axial Tape",
  "Hand Layup",
  "Woven Roving",
  "Benching Unit",
  "Benching Unit",
  "Benching Unit",
  "Flange",
  "Elbow,Reducer",
  "Lamination Joint",
  "Lamination Joint",
  "Tee",
  "Lamination Joint",
  "Lamination Joint",
  "Flange",
  "End Cap",
  "Lamination Kit,Build-up",
  "Flange",
  "Lamination Joint",
  "Lamination Joint",
  "Cowl",
  "Cowl",
  "Build-up",
  "Lamination Kit",
  "Lamination Joint",
  "Lamination Joint",
  "Lamination Joint",
  "Lamination Kit",
  "Lamination Kit",
  "Lamination Kit,Reinforcement Lamination Kit",
  "Lamination Kit",
  "Saddle - Cemented",
  "Lamination Joint",
  "Cowl",
  "Cowl",
  "CW Pipe",
  "CW Pipe",
  "Tee",
  "CW Pipe,YB Pipe",
  "Lamination Kit",
  "Lamination Joint",
  "Saddle - Cemented",
  "Flange",
  "Flange",
  "Tee",
  "Lamination Joint",
  "CW Pipe",
  "CW Pipe",
  "Lamination Joint",
  "Flange",
  "YB Coupler",
  "Lamination Joint",
  "Lamination Joint",
  "CW Pipe",
  "Saddle - Cemented,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup",
  "Lamination Joint",
  "Flange",
  "Lamination Kit",
  "Lamination Joint",
  "Flange",
  "Base Plate",
  "YB Pipe",
  "YB Pipe",
  "Lamination Joint",
  "Base Plate",
  "Cover Slab,Cover Slab-Str MH",
  "Cover Slab,Cover Slab-Str MH",
  "Puddle Flange",
  "cement Joint",
  "Lamination Joint,Reinforcement Lamination Joint",
  "Build-up",
  "CW Pipe",
  "Flange",
  "Base Plate",
  "Cover Slab,Cover Slab-Str MH",
  "Cover Slab,Cover Slab-Str MH",
  "CW Pipe",
  "Flange",
  "YB Pipe",
  "End Cap",
  "Lamination Joint",
  "CW Pipe",
  "End Cap",
  "Puddle Flange",
  "Flange",
  "CW Pipe",
  "Saddle - Cemented",
  "Flange",
  "Flange,Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup,Nozzle",
  "Saddle - Buildup",
  "Saddle - Cemented,Saddle - Buildup,Nozzle",
  "Saddle - Buildup",
  "Saddle - Buildup",
  "Lamination Joint"
];

const Series = [
  "Isophthalic CW LDP Non-Tensile",
  "Epoxy HW Tensile",
  "EST with FM Approval",
  "EST Conductive",
  "Epoxy Marine Tensile",
  "EMT Conductive",
  "EST High Temperature",
  "EHT Conductive",
  "EST, Potable Water",
  "EST Elec. Du France Series",
  "EST TOTAL Series",
  "EST Hydrogen",
  "Epoxy HW Non-Tensile",
  "ESN Conductive",
  "ESN, Potable Water",
  "Isophthalic HW Tensile",
  "Vinyl ester HW Tensile",
  "VST Conductive",
  "Isophthalic HW Non-Tensile",
  "Vinyl ester HW Non-Tensile",
  "Isophthalic CW LDP Tensile",
  "Isophthalic CW SDP Tensile",
  "Vinyl ester CW LDP Tensile",
  "VCT Conductive",
  "Vinyl ester CW SDP Tensile",
  "VCT SDP Conductive",
  "Epoxy CW LDP Tensile",
  "Epoxy CW SDP Tensile",
  "PCN, Australian Market",
  "PCN Imperial Series",
  "PCN Imperial Ductile Iron",
  "Isophthalic CW SDP Non-Tensile",
  "Vinyl ester CW LDP Non-Tensile",
  "VCN, Australian Market",
  "VCN Imperial Series",
  "VCN Imperial Ductile Iron",
  "Vinyl ester CW SDP Non-Tensile",
  "Epoxy CW LDP Non-Tensile",
  "ECN Imperial Series",
  "ECN Imperial Ductile Iron",
  "ECN CW SDP Non-Tensile",
  "ECN, DEWA",
  "ECN SDP, DEWA",
  "ECT, DEWA",
  "ECT SDP, DEWA",
  "ECN, SEWA",
  "ECN SDP, SEWA",
  "ECT, SEWA",
  "ECT SDP, SEWA",
  "Jacking, Metric, Iso, SS Coupler",
  "Jacking, Imperial, Iso, SS Coupler",
  "Jacking, Metric, VE, SS Coupler",
  "Jacking, Imperial, VE, SS Coupler",
  "Jacking, Metric, Epoxy, SS Coupler",
  "Jacking, Imperial, Epoxy, SS Coupler",
  "Jacking, Metric, Iso, CF Coupler",
  "Jacking, Imperial, Iso, CF Coupler",
  "Jacking, Metric, VE, CF Coupler",
  "Jacking, Imperial, VE, CF Coupler",
  "Jacking, Metric, Epoxy, CF Coupler",
  "Jacking, Imperial, Epoxy, CF Coupler",
  "Flowstrong Threaded HP Lines",
  "Geostrong Threaded Downhole",
  "Flowstrong",
  "Geostrong",
  "Fiberbond Chem",
  "Fiberbond OS (Offshore)",
  "Fiberbond OS",
  "Fiberbond OS, Conductive",
  "Flexstrong",
  "DM Sewer",
  "DM Irrigation",
  "DM (Pumping Station)",
  "PSN",
  "VSN",
  "PMP (For CB Flange)",
  "SE (For Flange)",
  "SE2 (For CB Flange)",
  "SEP (For flange)",
  "SEV (For flange)",
  "ADSS (Sewer)",
  "ADSC",
  "AlphaSand",
  "SPC",
  "PWD",
  "ROads",
  "STD (For Tank and MH Liner and Benching)",
  "VST B",
  "JTS For MH Liner",
  "VST A",
  "PST A",
  "EST",
  "CST",
  "DEWA",
  "EWT",
  "EMT",
  "CMT",
  "PCT A",
  "PCT B",
  "VCT A",
  "VCT B",
  "ECT",
  "PCN",
  "VCN",
  "ECN",
  "Ashghal",
  "PST B",
  "With Backdrop",
  "Yellow Box",
  "Australian STD",
  "ATH16",
  "20HV(CP)",
  "20FR20",
  "20FR16",
  "20HV(FDA)",
  "20FR-E",
  "20HV",
  "20JF16",
  "20JF",
  "AlphaCor70",
  "ALPHACOR55",
  "CSN",
  "ESN",
  "EWN",
  "Red Box",
  "Blue Box",
  "PMV (For CB Flange)",
  "DEWA SR",
  "Yellow Box - USA",
  "Red Box - USA",
  "Blue Box - USA",
  "Green Box",
  "Green Box - USA",
  "PCN Full Glass",
  "PCN 20% Sand",
  "PCN 25% Sand",
  "PCN 30% Sand",
  "PCN 35% Sand",
  "PCN 40% Sand",
  "PCN 45% Sand",
  "PCN 50% Sand",
  "110C",
  "110FW",
  "SE (For flange with PST Pipe)",
  "SE (For flange with VST Pipe)",
  "EDT",
  "EST-HT",
  "PCT SAT",
  "VCT SAT",
  "PCN-Jacking",
  "SEWA",
  "ECN-Jacking",
  "SEWA SR",
  "Isophthalic CW SDP Non-Tensile"
];

const Subseries = [
  "CN SDP",
  "LDP",
  "Jacking Product Stiffness class from 1,250 pa to 1,000,000 pa.",
  "Standard",
  "Epoxy FM Subseries",
  "Epoxy HW Subseries",
  "Fiberbond Chem Subseries",
  "Fiberbond OS Subseries",
  "Fiberbond OS Conductive, Subseries",
  "Flowstrong USA Subseries",
  "Geostrong USA Subseries",
  "USA Sub series"
];


const DesignCodes = [
  "FPI Standard Know-How",
  "ISO 14692",
  "Shell DEP",
  "API 15HR Monogram @65°C",
  "API 15HR Monogram @95°C",
  "API 15HR Design @65°C",
  "API 15HR Design @95°C",
  "API 15S",
  "PDO",
  "TOTAL Energy",
  "SABIC",
  "FM Unified",
  "FM AUH Plant",
  "FM KSA Plant",
  "FM EGY Plant",
  "FM NLD Plant"
];

const NominalDN1 = [
  "Nominal Metric Diameters, 15 mm up to 5,000 mm with 1 mm increments.",
  "Nominal Imperial Diameters, 1/8\" up to 200 with 1/8\" increments."
];

const NominalDN2 = [
  "Nominal Metric Diameters, 15 mm up to 5,000 mm with 1 mm increments.",
  "Nominal Imperial Diameters, 1/8\" up to 200 with 1/8\" increments."
];

const ItemMPR = [
  "Actual Metric Pressure 1.0 bar up to 500.9 bar with 0.1 bar increments.",
  "Actual Imperial Pressure 5 psi up to 9,000 psi with 5 psi increments."
];

const Ends = [
  "Plain End/Plan End",
  "Taper Bell/Taper Spigot",
  "Taper Spigot/Taper Spigot",
  "Cylindrical Bell/Conical Spigot",
  "Conical Spigot/Conical Spigot",
  "Fixed Bell Key-Lock, O-Ring",
  "Fixed Spigot Key-Lock, O-Ring",
  "Loose Bell, O-Ring",
  "Loose Spigot, O-Ring",
  "Fixed Bell Key-Lock, REKA Gasket",
  "Fixed Spigot Key-Lock, REKA Gasket",
  "Loose Bell, REKA Gasket",
  "Loose Spigot, REKA Gasket",
  "Flanged",
  "CN Spigot",
  "Jacking Spigot",
  "AC Spigot",
  "Threaded Spigot",
  "Threaded Bell, Integral",
  "Threaded Bell, Coupler",
  "NPT Thread",
  "BSP Thread",
  "Flexstrong Fitting"
];

const DrillingEnd1 = [
  "ASA 150",
  "ASA 300",
  "ASA 600",
  "PN 6",
  "PN 10",
  "PN 16",
  "PN 25",
  "PN 40",
  "API 75",
  "API 150",
  "API 300",
  "JIS 5K",
  "JIS 10K",
  "JIS 16K",
  "MSS 300",
  "PN 50",
  "PN 63",
  "AS 2129-2000",
  "ASA 900",
  "ASA 1,500",
  "ASA 2,500",
  "Type 1",
  "Type 2",
  "Type3",
  "Special",
  "Not Applicable"
];




export {TypeData, SubTypeData, Composition, Series, Subseries, DesignCodes,NominalDN1,NominalDN2, ItemMPR, Ends,DrillingEnd1};
